/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { 
  Sun, 
  Moon, 
  Smartphone, 
  Monitor, 
  Info, 
  Star, 
  Share2, 
  ShieldCheck, 
  X, 
  CheckCircle, 
  Heart, 
  ChevronRight, 
  Sparkles, 
  Send,
  Languages,
  RotateCw,
  FileText,
  PhoneCall,
  Trash2
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface SettingsViewProps {
  isDarkMode: boolean;
  setIsDarkMode: (val: boolean) => void;
  themeMode: 'light' | 'dark' | 'system';
  setThemeMode: (val: 'light' | 'dark' | 'system') => void;
  language: 'en' | 'hi';
  setLanguage: (val: 'en' | 'hi') => void;
  isPhoneFrame: boolean;
  setIsPhoneFrame: (val: boolean) => void;
  vibration: boolean;
  setVibration: (val: boolean) => void;
  favoritesCount: number;
  onRestoreDefaults: () => void;
}

const TRANSLATIONS = {
  en: {
    settingsTitle: "Settings",
    settingsSubtitle: "Configure your CalcNova experience",
    themeTitle: "THEME DISPLAY",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemTheme: "System Theme",
    langTitle: "LANGUAGE / भाषा",
    english: "English",
    hindi: "हिन्दी (Hindi)",
    actionsTitle: "ACTIONS & REVIEWS",
    rateTitle: "Rate CalcNova",
    rateSub: "Share your rating and feedback with us",
    shareTitle: "Share App",
    shareSub: "Recommend CalcNova to friends & classmates",
    privacyTitle: "Privacy Policy",
    privacySub: "Read our zero-data tracking policy",
    termsTitle: "Terms & Conditions",
    termsSub: "Read our service terms & guidelines",
    contactTitle: "Contact Us",
    contactSub: "Get in touch with our support team",
    aboutTitle: "About App",
    aboutSub: "Specifications, framework details & build changelog",
    nativeTitle: "NATIVE CONTROLS",
    frameTitle: "Android Frame View",
    frameSub: "Simulate a high-fidelity Material 3 phone view",
    hapticTitle: "Haptic Vibration Feedback",
    hapticSub: "Simulate tactile Android haptics on selection",
    appStatsTitle: "APP SUMMARY & VERSION",
    favoritesCount: "Saved Favorites",
    designSystem: "Design System",
    releaseVersion: "Release Version",
    restoreTitle: "RESTORE DEFAULTS",
    restoreBtn: "Reset App to Factory Settings",
    restoreSub: "Clear all local logs, favorites, and settings",
    restoreConfirmTitle: "Restore Default Settings?",
    restoreConfirmDesc: "Are you sure you want to restore defaults? This will reset all your favorites, configuration parameters, theme, and language. Recent visits logs will be wiped clean.",
    restoreCancel: "Cancel",
    restoreProceed: "Reset Now",
    footerText1: "CalcNova • Crafted with Love & Precision",
    footerText2: "Dynamic UI powered by React + Tailwind + Motion",
    contactFormName: "Your Name",
    contactFormEmail: "Email Address",
    contactFormCategory: "Select Query Category",
    contactFormCategoryBug: "Bug Report",
    contactFormCategoryFeature: "Feature Suggestion",
    contactFormCategorySupport: "General Inquiry",
    contactFormMessage: "Type your message...",
    contactSubmitBtn: "Send Message",
    contactFormErrName: "Please enter your name",
    contactFormErrEmail: "Please enter a valid email",
    contactFormErrMessage: "Please enter a message (min 10 characters)",
    contactSuccess: "Message sent successfully! Our support team will review it.",
    rateSuccessToast: "Thank you for supporting CalcNova!",
    restoreSuccessToast: "All settings and favorites restored successfully!",
    termsContent1: "1. Acceptance of Terms",
    termsContent1Text: "By accessing and using CalcNova, you agree to be bound by these Terms and Conditions. If you do not agree, please refrain from using the application.",
    termsContent2: "2. Personal & Educational Use",
    termsContent2Text: "CalcNova is designed solely for personal and educational calculation purposes. Results generated by calculations should be double-checked for critical professional decisions.",
    termsContent3: "3. Service Availability",
    termsContent3Text: "CalcNova operates client-side inside your browser sandbox. We do not guarantee uninterrupted access or that calculations will fit every edge case scenario. Users are solely responsible for local storage backups.",
    termsContent4: "4. Intellectual Property",
    termsContent4Text: "All layout designs, code modules, and branding materials are copyrighted assets of CalcNova. Re-distribution or commercial framing of this application without license is strictly prohibited.",
    contactModalTitle: "Connect with Us",
    contactModalDesc: "Have a feature request or found a calculation bug? Fill out this quick form and we'll reply shortly.",
    termsModalTitle: "Terms of Service",
    aboutHeader: "CalcNova Suite",
    aboutSubHeader: "Stable Release Build",
    aboutDescTitle: "What is CalcNova?",
    aboutDescText: "CalcNova is a premier, offline-first calculation workshop designed in strict compliance with the Material 3 Design Specification. Built for high precision and polished interactive states, it gathers financial estimators, physical metrics, unit converters, time difference calculators, and academic logs in a unified, beautiful workspace.",
    aboutModulesTitle: "Supported Core Modules",
    aboutChangelogTitle: "Changelog (Latest Updates)",
    toastThemeLight: "Light Theme activated",
    toastThemeDark: "Dark Theme activated",
    toastThemeSystem: "System Theme activated",
    toastLanguageEn: "Language set to English",
    toastLanguageHi: "भाषा हिंदी में सेट की गई",
    toastFrameOn: "Android Frame simulated",
    toastFrameOff: "Switched to Full View",
    toastHapticOn: "Haptic feedback enabled",
    toastHapticOff: "Haptic feedback disabled",
    toastRateSet: "Rating updated!",
    toastRateSub: "Thanks for rating us!"
  },
  hi: {
    settingsTitle: "सेटिंग्स",
    settingsSubtitle: "अपने CalcNova अनुभव को कॉन्फ़िगर करें",
    themeTitle: "थीम डिस्प्ले",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemTheme: "सिस्टम थीम",
    langTitle: "भाषा / LANGUAGE",
    english: "English (अंग्रेजी)",
    hindi: "हिन्दी",
    actionsTitle: "क्रियाएं और समीक्षाएं",
    rateTitle: "CalcNova को रेट करें",
    rateSub: "अपनी रेटिंग और फीडबैक हमारे साथ साझा करें",
    shareTitle: "ऐप साझा करें",
    shareSub: "दोस्तों और सहपाठियों को CalcNova की सिफारिश करें",
    privacyTitle: "गोपनीयता नीति",
    privacySub: "हमारी शून्य-डेटा ट्रैकिंग नीति पढ़ें",
    termsTitle: "नियम और शर्तें",
    termsSub: "हमारी सेवा की शर्तें और दिशानिर्देश पढ़ें",
    contactTitle: "हमसे संपर्क करें",
    contactSub: "हमारी सहायता टीम से संपर्क करें",
    aboutTitle: "ऐप के बारे में",
    aboutSub: "विनिर्देशों, फ्रेमवर्क विवरण और बिल्ड चेंजलॉग",
    nativeTitle: "मूल नियंत्रण",
    frameTitle: "एंड्रॉइड फ्रेम दृश्य",
    frameSub: "मटीरियल 3 फोन व्यू का अनुकरण करें",
    hapticTitle: "हैप्टिक कंपन फीडबैक",
    hapticSub: "चयन पर स्पर्श संबंधी हैप्टिक्स का अनुकरण करें",
    appStatsTitle: "ऐप सारांश और संस्करण",
    favoritesCount: "सहेजे गए पसंदीदा",
    designSystem: "डिज़ाइन सिस्टम",
    releaseVersion: "रिलीज संस्करण",
    restoreTitle: "फ़ैक्टरी रीसेट",
    restoreBtn: "ऐप को फ़ैक्टरी सेटिंग्स पर रीसेट करें",
    restoreSub: "सभी स्थानीय लॉग, पसंदीदा और सेटिंग्स साफ़ करें",
    restoreConfirmTitle: "डिफ़ॉल्ट सेटिंग्स पुनर्स्थापित करें?",
    restoreConfirmDesc: "क्या आप वाकई सेटिंग्स रीसेट करना चाहते हैं? इससे आपके सहेजे गए पसंदीदा, कॉन्फ़िगरेशन पैरामीटर, थीम और भाषा रीसेट हो जाएंगे और इतिहास मिटा दिया जाएगा।",
    restoreCancel: "रद्द करें",
    restoreProceed: "अभी रीसेट करें",
    footerText1: "CalcNova • प्यार और सटीकता के साथ निर्मित",
    footerText2: "रिएक्ट + टेलविंड + मोशन द्वारा संचालित गतिशील यूआई",
    contactFormName: "आपका नाम",
    contactFormEmail: "ईमेल पता",
    contactFormCategory: "प्रश्न श्रेणी चुनें",
    contactFormCategoryBug: "बग रिपोर्ट (त्रुटि)",
    contactFormCategoryFeature: "सुझाव (सुविधा)",
    contactFormCategorySupport: "सामान्य प्रश्न",
    contactFormMessage: "अपना संदेश टाइप करें...",
    contactSubmitBtn: "संदेश भेजें",
    contactFormErrName: "कृपया अपना नाम दर्ज करें",
    contactFormErrEmail: "कृपया एक वैध ईमेल दर्ज करें",
    contactFormErrMessage: "कृपया एक संदेश दर्ज करें (न्यूनतम 10 वर्ण)",
    contactSuccess: "संदेश सफलतापूर्वक भेजा गया! हमारी टीम इसकी समीक्षा करेगी।",
    rateSuccessToast: "CalcNova का समर्थन करने के लिए धन्यवाद!",
    restoreSuccessToast: "सभी सेटिंग्स और पसंदीदा सफलतापूर्वक रीसेट कर दिए गए हैं!",
    termsContent1: "1. शर्तों की स्वीकृति",
    termsContent1Text: "CalcNova तक पहुँचने और उपयोग करके, आप इन नियमों और शर्तों से बाध्य होने के लिए सहमत हैं। यदि आप सहमत नहीं हैं, तो कृपया ऐप का उपयोग न करें।",
    termsContent2: "2. व्यक्तिगत और शैक्षिक उपयोग",
    termsContent2Text: "CalcNova पूरी तरह से व्यक्तिगत और शैक्षिक गणना उद्देश्यों के लिए डिज़ाइन किया गया है। महत्वपूर्ण निर्णयों के लिए परिणामों की दोबारा जांच की जानी चाहिए।",
    termsContent3: "3. सेवा की उपलब्धता",
    termsContent3Text: "CalcNova आपके ब्राउज़र सैंडबॉक्स के अंदर क्लाइंट-साइड संचालित होता है। हम निर्बाध पहुँच की गारंटी नहीं देते हैं। उपयोगकर्ता स्थानीय बैकअप के लिए स्वयं जिम्मेदार हैं।",
    termsContent4: "4. बौद्धिक संपदा",
    termsContent4Text: "सभी लेआउट डिज़ाइन, कोड मॉड्यूल और ब्रांडिंग सामग्री CalcNova की कॉपीराइट संपत्ति हैं। बिना अनुमति के व्यावसायिक उपयोग सख्त वर्जित है।",
    contactModalTitle: "हमसे जुड़ें",
    contactModalDesc: "कोई सुझाव है या गणना में कोई त्रुटि मिली है? इस त्वरित फ़ॉर्म को भरें और हम जल्द ही उत्तर देंगे।",
    termsModalTitle: "सेवा की शर्तें",
    aboutHeader: "CalcNova सूट",
    aboutSubHeader: "स्थिर रिलीज संस्करण",
    aboutDescTitle: "CalcNova क्या है?",
    aboutDescText: "CalcNova एक अग्रणी, ऑफलाइन-फर्स्ट कैलकुलेशन वर्कशॉप है जिसे मटीरियल 3 डिज़ाइन विशिष्टता के सख्त अनुपालन में डिज़ाइन किया गया है। उच्च सटीकता और पॉलिश इंटरैक्टिव राज्यों के लिए निर्मित, यह वित्तीय योजनाकारों, शारीरिक संकेतकों, इकाई कन्वर्टर्स, समय अंतर कैलकुलेटर और शैक्षणिक लॉग को एक सुंदर कार्यकार्य में एकत्रित करता है।",
    aboutModulesTitle: "समर्थित मुख्य मॉड्यूल",
    aboutChangelogTitle: "चेंजलॉग (नवीनतम अपडेट)",
    toastThemeLight: "लाइट थीम सक्रिय हो गई",
    toastThemeDark: "डार्क थीम सक्रिय हो गई",
    toastThemeSystem: "सिस्टम थीम सक्रिय हो गई",
    toastLanguageEn: "अंग्रेजी भाषा सेट की गई",
    toastLanguageHi: "भाषा हिंदी में सेट की गई",
    toastFrameOn: "एंड्रॉइड फ्रेम का अनुकरण किया गया",
    toastFrameOff: "पूर्ण दृश्य पर स्विच किया गया",
    toastHapticOn: "हैप्टिक फीडबैक सक्षम किया गया",
    toastHapticOff: "हैप्टिक फीडबैक अक्षम किया गया",
    toastRateSet: "रेटिंग अपडेट की गई!",
    toastRateSub: "रेटिंग देने के लिए धन्यवाद!"
  }
};

export default function SettingsView({
  isDarkMode,
  setIsDarkMode,
  themeMode,
  setThemeMode,
  language,
  setLanguage,
  isPhoneFrame,
  setIsPhoneFrame,
  vibration,
  setVibration,
  favoritesCount,
  onRestoreDefaults
}: SettingsViewProps) {
  // Modal states
  const [showRateModal, setShowRateModal] = useState(false);
  const [showPrivacyModal, setShowPrivacyModal] = useState(false);
  const [showTermsModal, setShowTermsModal] = useState(false);
  const [showContactModal, setShowContactModal] = useState(false);
  const [showAboutModal, setShowAboutModal] = useState(false);
  const [showRestoreModal, setShowRestoreModal] = useState(false);

  // Rating States
  const [rating, setRating] = useState<number>(0);
  const [hoverRating, setHoverRating] = useState<number>(0);
  const [feedback, setFeedback] = useState<string>('');
  const [ratingSubmitted, setRatingSubmitted] = useState<boolean>(false);
  
  // Persistent Saved Rating
  const [savedRating, setSavedRating] = useState<{ score: number; comment: string; date: string } | null>(() => {
    const saved = localStorage.getItem('calcnova_user_rating');
    return saved ? JSON.parse(saved) : null;
  });

  // Contact Us Form States
  const [contactName, setContactName] = useState('');
  const [contactEmail, setContactEmail] = useState('');
  const [contactCategory, setContactCategory] = useState('bug');
  const [contactMessage, setContactMessage] = useState('');
  const [contactErr, setContactErr] = useState('');
  const [contactSuccessMsg, setContactSuccessMsg] = useState(false);

  // Toast notification state
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const t = TRANSLATIONS[language];

  // Auto-dismiss toast
  useEffect(() => {
    if (toastMessage) {
      const timer = setTimeout(() => {
        setToastMessage(null);
      }, 2500);
      return () => clearTimeout(timer);
    }
  }, [toastMessage]);

  const showToast = (message: string) => {
    setToastMessage(message);
    // Trigger simulated haptic
    if (vibration && navigator.vibrate) {
      navigator.vibrate(15);
    }
  };

  // Handler for sharing
  const handleShareApp = async () => {
    const shareData = {
      title: 'CalcNova Premium',
      text: 'Check out CalcNova, the all-in-one Material 3 calculation companion. It has financial planners, health trackers, education evaluators, unit converters, and more!',
      url: window.location.origin
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        showToast(language === 'hi' ? 'साझा किया गया! धन्यवाद।' : 'Shared successfully! Thanks for spreading the word.');
      } catch (err) {
        copyShareLink();
      }
    } else {
      copyShareLink();
    }
  };

  const copyShareLink = () => {
    navigator.clipboard.writeText(window.location.origin);
    showToast(language === 'hi' ? 'लिंक क्लिपबोर्ड पर कॉपी हो गया!' : 'Share link copied to clipboard!');
  };

  // Handler for rating submission
  const handleSubmitRating = (e: React.FormEvent) => {
    e.preventDefault();
    if (rating === 0) {
      showToast(language === 'hi' ? 'कृपया पहले स्टार रेटिंग चुनें!' : 'Please select a star rating first!');
      return;
    }

    const payload = {
      score: rating,
      comment: feedback.trim(),
      date: new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
    };

    localStorage.setItem('calcnova_user_rating', JSON.stringify(payload));
    setSavedRating(payload);
    setRatingSubmitted(true);
    
    if (vibration && navigator.vibrate) {
      navigator.vibrate([30, 50, 30]);
    }

    setTimeout(() => {
      setShowRateModal(false);
      setRatingSubmitted(false);
      showToast(t.rateSuccessToast);
    }, 1800);
  };

  // Handler for Contact Us form submission
  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setContactErr('');

    if (!contactName.trim()) {
      setContactErr(t.contactFormErrName);
      return;
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!contactEmail.trim() || !emailRegex.test(contactEmail)) {
      setContactErr(t.contactFormErrEmail);
      return;
    }
    if (contactMessage.trim().length < 10) {
      setContactErr(t.contactFormErrMessage);
      return;
    }

    // Save locally or log simulated contact message
    const newMessage = {
      name: contactName.trim(),
      email: contactEmail.trim(),
      category: contactCategory,
      message: contactMessage.trim(),
      date: new Date().toISOString()
    };
    
    const existing = localStorage.getItem('calcnova_contact_messages');
    const messages = existing ? JSON.parse(existing) : [];
    messages.push(newMessage);
    localStorage.setItem('calcnova_contact_messages', JSON.stringify(messages));

    setContactSuccessMsg(true);
    if (vibration && navigator.vibrate) {
      navigator.vibrate([20, 20]);
    }

    setTimeout(() => {
      setShowContactModal(false);
      setContactSuccessMsg(false);
      setContactName('');
      setContactEmail('');
      setContactMessage('');
      showToast(t.contactSuccess);
    }, 2000);
  };

  // Handler for Restore Defaults
  const handleRestoreDefaultsConfirm = () => {
    onRestoreDefaults();
    setShowRestoreModal(false);
    showToast(t.restoreSuccessToast);
  };

  return (
    <div className="flex-1 overflow-y-auto no-scrollbar p-5 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className={`text-2xl font-extrabold font-display tracking-tight ${isDarkMode ? 'text-white' : 'text-primary'}`}>
            {t.settingsTitle}
          </h1>
          <p className={`text-xs mt-1 font-semibold tracking-wide uppercase ${isDarkMode ? 'text-slate-400' : 'text-slate-500'}`}>
            {t.settingsSubtitle}
          </p>
        </div>
        <div className="p-2 bg-primary/10 dark:bg-blue-500/10 rounded-2xl text-primary dark:text-blue-400">
          <Languages size={20} className="animate-pulse" />
        </div>
      </div>

      {/* THEME CONTROL CARD (Light, Dark, System Theme) */}
      <div className={`p-4 rounded-3xl m3-card-shadow ${isDarkMode ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'} space-y-4`}>
        <h3 className={`text-[10px] font-black tracking-widest uppercase mb-1 ${isDarkMode ? 'text-blue-400' : 'text-primary'}`}>
          {t.themeTitle}
        </h3>
        
        <div className="grid grid-cols-3 gap-2">
          {/* Light Theme */}
          <button
            onClick={() => {
              setThemeMode('light');
              showToast(t.toastThemeLight);
            }}
            className={`p-3 rounded-2xl border transition-all flex flex-col items-center justify-center gap-2 cursor-pointer ${
              themeMode === 'light'
                ? 'bg-blue-500/10 border-blue-500 text-blue-600 font-bold'
                : isDarkMode 
                  ? 'bg-slate-800/30 border-slate-800 text-slate-400 hover:bg-slate-800/50'
                  : 'bg-slate-50 border-slate-100 text-slate-600 hover:bg-slate-100/60'
            }`}
          >
            <Sun size={18} className={themeMode === 'light' ? 'text-amber-500 animate-spin-slow' : 'text-slate-400'} />
            <span className="text-[10px] font-bold text-center leading-tight">{t.lightMode}</span>
          </button>

          {/* Dark Theme */}
          <button
            onClick={() => {
              setThemeMode('dark');
              showToast(t.toastThemeDark);
            }}
            className={`p-3 rounded-2xl border transition-all flex flex-col items-center justify-center gap-2 cursor-pointer ${
              themeMode === 'dark'
                ? 'bg-blue-600/20 border-blue-500 text-blue-400 font-bold'
                : isDarkMode 
                  ? 'bg-slate-800/30 border-slate-800 text-slate-400 hover:bg-slate-800/50'
                  : 'bg-slate-50 border-slate-100 text-slate-600 hover:bg-slate-100/60'
            }`}
          >
            <Moon size={18} className={themeMode === 'dark' ? 'text-blue-400 animate-pulse' : 'text-slate-400'} />
            <span className="text-[10px] font-bold text-center leading-tight">{t.darkMode}</span>
          </button>

          {/* System Theme */}
          <button
            onClick={() => {
              setThemeMode('system');
              showToast(t.toastThemeSystem);
            }}
            className={`p-3 rounded-2xl border transition-all flex flex-col items-center justify-center gap-2 cursor-pointer ${
              themeMode === 'system'
                ? 'bg-purple-500/10 border-purple-500 text-purple-600 dark:text-purple-400 font-bold'
                : isDarkMode 
                  ? 'bg-slate-800/30 border-slate-800 text-slate-400 hover:bg-slate-800/50'
                  : 'bg-slate-50 border-slate-100 text-slate-600 hover:bg-slate-100/60'
            }`}
          >
            <Monitor size={18} className={themeMode === 'system' ? 'text-purple-500 dark:text-purple-400' : 'text-slate-400'} />
            <span className="text-[10px] font-bold text-center leading-tight">{t.systemTheme}</span>
          </button>
        </div>
      </div>

      {/* LANGUAGE SELECTOR CARD */}
      <div className={`p-4 rounded-3xl m3-card-shadow ${isDarkMode ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'} space-y-4`}>
        <h3 className={`text-[10px] font-black tracking-widest uppercase mb-1 ${isDarkMode ? 'text-blue-400' : 'text-primary'}`}>
          {t.langTitle}
        </h3>
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={() => {
              setLanguage('en');
              showToast(t.toastLanguageEn);
            }}
            className={`p-3.5 rounded-2xl border transition-all flex items-center justify-center gap-2.5 cursor-pointer text-xs font-black ${
              language === 'en'
                ? 'bg-blue-500/10 border-blue-500 text-blue-600 dark:text-blue-400 shadow-sm'
                : isDarkMode 
                  ? 'bg-slate-800/30 border-slate-850 text-slate-400 hover:bg-slate-800/50'
                  : 'bg-slate-50 border-slate-150 text-slate-600 hover:bg-slate-100'
            }`}
          >
            <span className="text-sm font-mono uppercase bg-blue-500/10 text-blue-600 dark:text-blue-400 px-1.5 py-0.5 rounded-md font-black">A</span>
            <span>{t.english}</span>
          </button>

          <button
            onClick={() => {
              setLanguage('hi');
              showToast(t.toastLanguageHi);
            }}
            className={`p-3.5 rounded-2xl border transition-all flex items-center justify-center gap-2.5 cursor-pointer text-xs font-black ${
              language === 'hi'
                ? 'bg-blue-500/10 border-blue-500 text-blue-600 dark:text-blue-400 shadow-sm'
                : isDarkMode 
                  ? 'bg-slate-800/30 border-slate-850 text-slate-400 hover:bg-slate-800/50'
                  : 'bg-slate-50 border-slate-150 text-slate-600 hover:bg-slate-100'
            }`}
          >
            <span className="text-sm font-sans bg-blue-500/10 text-blue-600 dark:text-blue-400 px-1.5 py-0.5 rounded-md font-black">अ</span>
            <span>{t.hindi}</span>
          </button>
        </div>
      </div>

      {/* APP ACTIONS CARD (Rate, Share, Privacy, Terms, Contact, About) */}
      <div className={`p-4 rounded-3xl m3-card-shadow ${isDarkMode ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'} space-y-1`}>
        <h3 className={`text-[10px] font-black tracking-widest uppercase mb-3 px-1 ${isDarkMode ? 'text-blue-400' : 'text-primary'}`}>
          {t.actionsTitle}
        </h3>

        {/* Rate App */}
        <button
          onClick={() => {
            if (savedRating) {
              setRating(savedRating.score);
              setFeedback(savedRating.comment);
            } else {
              setRating(0);
              setFeedback('');
            }
            setShowRateModal(true);
          }}
          className={`w-full flex items-center justify-between p-2.5 rounded-2xl transition-colors cursor-pointer ${
            isDarkMode ? 'hover:bg-slate-800/60' : 'hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDarkMode ? 'bg-amber-500/10 text-amber-400' : 'bg-amber-50 text-amber-500'}`}>
              <Star size={18} fill={savedRating ? 'currentColor' : 'none'} />
            </div>
            <div className="text-left">
              <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
                {t.rateTitle}
              </span>
              <span className="text-[10px] text-slate-500 block font-medium">
                {savedRating ? `★ ${savedRating.score} / 5` : t.rateSub}
              </span>
            </div>
          </div>
          <ChevronRight size={16} className="text-slate-400" />
        </button>

        {/* Share App */}
        <button
          onClick={handleShareApp}
          className={`w-full flex items-center justify-between p-2.5 rounded-2xl transition-colors cursor-pointer border-t dark:border-slate-800/40 mt-1 pt-3 ${
            isDarkMode ? 'hover:bg-slate-800/60' : 'hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDarkMode ? 'bg-blue-500/10 text-blue-400' : 'bg-blue-50 text-blue-600'}`}>
              <Share2 size={18} />
            </div>
            <div className="text-left">
              <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
                {t.shareTitle}
              </span>
              <span className="text-[10px] text-slate-500 block font-medium">
                {t.shareSub}
              </span>
            </div>
          </div>
          <ChevronRight size={16} className="text-slate-400" />
        </button>

        {/* Privacy Policy */}
        <button
          onClick={() => setShowPrivacyModal(true)}
          className={`w-full flex items-center justify-between p-2.5 rounded-2xl transition-colors cursor-pointer border-t dark:border-slate-800/40 mt-1 pt-3 ${
            isDarkMode ? 'hover:bg-slate-800/60' : 'hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDarkMode ? 'bg-emerald-500/10 text-emerald-400' : 'bg-emerald-50 text-emerald-600'}`}>
              <ShieldCheck size={18} />
            </div>
            <div className="text-left">
              <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
                {t.privacyTitle}
              </span>
              <span className="text-[10px] text-slate-500 block font-medium">
                {t.privacySub}
              </span>
            </div>
          </div>
          <ChevronRight size={16} className="text-slate-400" />
        </button>

        {/* Terms & Conditions */}
        <button
          onClick={() => setShowTermsModal(true)}
          className={`w-full flex items-center justify-between p-2.5 rounded-2xl transition-colors cursor-pointer border-t dark:border-slate-800/40 mt-1 pt-3 ${
            isDarkMode ? 'hover:bg-slate-800/60' : 'hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDarkMode ? 'bg-orange-500/10 text-orange-400' : 'bg-orange-50 text-orange-600'}`}>
              <FileText size={18} />
            </div>
            <div className="text-left">
              <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
                {t.termsTitle}
              </span>
              <span className="text-[10px] text-slate-500 block font-medium">
                {t.termsSub}
              </span>
            </div>
          </div>
          <ChevronRight size={16} className="text-slate-400" />
        </button>

        {/* Contact Us */}
        <button
          onClick={() => setShowContactModal(true)}
          className={`w-full flex items-center justify-between p-2.5 rounded-2xl transition-colors cursor-pointer border-t dark:border-slate-800/40 mt-1 pt-3 ${
            isDarkMode ? 'hover:bg-slate-800/60' : 'hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDarkMode ? 'bg-cyan-500/10 text-cyan-400' : 'bg-cyan-50 text-cyan-600'}`}>
              <PhoneCall size={18} />
            </div>
            <div className="text-left">
              <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
                {t.contactTitle}
              </span>
              <span className="text-[10px] text-slate-500 block font-medium">
                {t.contactSub}
              </span>
            </div>
          </div>
          <ChevronRight size={16} className="text-slate-400" />
        </button>

        {/* About App */}
        <button
          onClick={() => setShowAboutModal(true)}
          className={`w-full flex items-center justify-between p-2.5 rounded-2xl transition-colors cursor-pointer border-t dark:border-slate-800/40 mt-1 pt-3 ${
            isDarkMode ? 'hover:bg-slate-800/60' : 'hover:bg-slate-50'
          }`}
        >
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-xl ${isDarkMode ? 'bg-purple-500/10 text-purple-400' : 'bg-purple-50 text-purple-600'}`}>
              <Info size={18} />
            </div>
            <div className="text-left">
              <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>
                {t.aboutTitle}
              </span>
              <span className="text-[10px] text-slate-500 block font-medium">
                {t.aboutSub}
              </span>
            </div>
          </div>
          <ChevronRight size={16} className="text-slate-400" />
        </button>
      </div>

      {/* ADDITIONAL PREFERENCES CARD (Frame & Vibration) */}
      <div className={`p-4 rounded-3xl m3-card-shadow ${isDarkMode ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'} space-y-4`}>
        <h3 className={`text-[10px] font-black tracking-widest uppercase mb-1 ${isDarkMode ? 'text-blue-400' : 'text-primary'}`}>
          {t.nativeTitle}
        </h3>

        {/* Device Mode Toggle */}
        <div className="flex items-center justify-between py-1">
          <div>
            <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>{t.frameTitle}</span>
            <span className="text-[10px] text-slate-500 font-medium">{t.frameSub}</span>
          </div>
          <button
            onClick={() => {
              setIsPhoneFrame(!isPhoneFrame);
              showToast(isPhoneFrame ? t.toastFrameOff : t.toastFrameOn);
            }}
            className={`w-12 h-6 rounded-full p-1 transition-colors duration-300 relative cursor-pointer ${isPhoneFrame ? 'bg-primary' : 'bg-slate-300'}`}
          >
            <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 flex items-center justify-center text-[8px] ${isPhoneFrame ? 'translate-x-6' : ''}`}>
              {isPhoneFrame ? <Smartphone size={10} className="text-primary" /> : <Monitor size={10} className="text-slate-400" />}
            </div>
          </button>
        </div>

        {/* Simulated Vibration Feedback */}
        <div className="flex items-center justify-between py-1 border-t dark:border-slate-800/60 pt-3">
          <div>
            <span className={`text-sm font-semibold block ${isDarkMode ? 'text-slate-200' : 'text-slate-800'}`}>{t.hapticTitle}</span>
            <span className="text-[10px] text-slate-500 font-medium">{t.hapticSub}</span>
          </div>
          <button
            onClick={() => {
              setVibration(!vibration);
              showToast(vibration ? t.toastHapticOff : t.toastHapticOn);
            }}
            className={`w-12 h-6 rounded-full p-1 transition-colors duration-300 relative cursor-pointer ${vibration ? 'bg-primary' : 'bg-slate-300'}`}
          >
            <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${vibration ? 'translate-x-6' : ''}`}></div>
          </button>
        </div>
      </div>

      {/* RESTORE DEFAULTS DANGER BANNER */}
      <div className={`p-4 rounded-3xl m3-card-shadow ${isDarkMode ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'} space-y-3`}>
        <h3 className={`text-[10px] font-black tracking-widest uppercase text-red-500 dark:text-red-400`}>
          {t.restoreTitle}
        </h3>
        <p className="text-[10px] text-slate-500 font-medium leading-relaxed">
          {t.restoreSub}
        </p>
        <button
          onClick={() => {
            if (vibration && navigator.vibrate) navigator.vibrate(30);
            setShowRestoreModal(true);
          }}
          className="w-full py-2.5 border border-dashed border-red-500/40 text-red-500 hover:bg-red-500/5 transition-all text-xs font-black rounded-2xl flex items-center justify-center gap-1.5 cursor-pointer"
        >
          <Trash2 size={13} />
          <span>{t.restoreBtn}</span>
        </button>
      </div>

      {/* APP METADATA SUMMARY */}
      <div className={`p-4 rounded-3xl m3-card-shadow ${isDarkMode ? 'bg-slate-900 border border-slate-800' : 'bg-white border border-slate-100'} space-y-3 text-xs`}>
        <div className="flex justify-between items-center">
          <span className="text-slate-500 font-medium">{t.favoritesCount}</span>
          <span className={`font-mono font-bold px-2 py-0.5 rounded-full ${isDarkMode ? 'bg-slate-800 text-amber-400' : 'bg-blue-50 text-blue-600'}`}>
            ★ {favoritesCount} {language === 'hi' ? 'आइटम' : 'items'}
          </span>
        </div>

        <div className="flex justify-between items-center border-t dark:border-slate-800/60 pt-2.5">
          <span className="text-slate-500 font-medium">{t.designSystem}</span>
          <span className={`font-semibold ${isDarkMode ? 'text-slate-300' : 'text-slate-700'}`}>Material You (M3)</span>
        </div>

        <div className="flex justify-between items-center border-t dark:border-slate-800/60 pt-2.5">
          <span className="text-slate-500 font-medium">{t.releaseVersion}</span>
          <span className="text-slate-500 font-mono font-bold flex items-center gap-1 text-[11px] bg-emerald-500/10 text-emerald-600 dark:bg-emerald-500/20 dark:text-emerald-400 px-2 py-0.5 rounded-full">
            v2.1.0 Premium
          </span>
        </div>
      </div>

      {/* FOOTER */}
      <div className="text-center space-y-1 py-4">
        <p className="text-xs text-slate-500 font-semibold">{t.footerText1}</p>
        <p className="text-[10px] text-slate-600 font-medium">{t.footerText2}</p>
      </div>

      {/* ========================================================
          TOAST ALERT POPUP (Material Style)
          ======================================================== */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div
            initial={{ opacity: 0, y: 50, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            className="fixed bottom-20 left-1/2 -translate-x-1/2 z-50 w-auto max-w-[90%] px-4 py-2.5 rounded-full bg-slate-900 dark:bg-white text-white dark:text-slate-950 shadow-xl flex items-center gap-2 text-xs font-semibold"
          >
            <Sparkles size={14} className="text-amber-400 shrink-0" />
            <span>{toastMessage}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ========================================================
          RESTORE DEFAULTS MODAL
          ======================================================== */}
      <AnimatePresence>
        {showRestoreModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowRestoreModal(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-xs"
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className={`relative w-full max-w-sm rounded-3xl p-6 shadow-2xl z-10 overflow-hidden ${
                isDarkMode ? 'bg-slate-900 text-white border border-slate-800' : 'bg-white text-slate-900 border border-slate-100'
              }`}
            >
              <div className="text-center space-y-4">
                <div className="inline-flex p-3 rounded-full bg-red-500/10 text-red-500">
                  <Trash2 size={28} />
                </div>

                <div className="space-y-1.5">
                  <h3 className="text-lg font-black font-display text-red-500 dark:text-red-400">
                    {t.restoreConfirmTitle}
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
                    {t.restoreConfirmDesc}
                  </p>
                </div>

                <div className="flex gap-3 pt-2">
                  <button
                    onClick={() => setShowRestoreModal(false)}
                    className="flex-1 py-2.5 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 rounded-full text-xs font-bold transition-colors cursor-pointer"
                  >
                    {t.restoreCancel}
                  </button>
                  <button
                    onClick={handleRestoreDefaultsConfirm}
                    className="flex-1 py-2.5 bg-red-600 hover:bg-red-700 text-white rounded-full text-xs font-bold transition-colors cursor-pointer"
                  >
                    {t.restoreProceed}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ========================================================
          RATE APP MODAL
          ======================================================== */}
      <AnimatePresence>
        {showRateModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowRateModal(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-xs"
            />

            {/* Modal Body */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className={`relative w-full max-w-sm rounded-3xl p-6 shadow-2xl z-10 overflow-hidden ${
                isDarkMode ? 'bg-slate-900 text-white border border-slate-800' : 'bg-white text-slate-900 border border-slate-100'
              }`}
            >
              {/* Top Close Button */}
              <button
                onClick={() => setShowRateModal(false)}
                className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-slate-500/10 cursor-pointer transition-colors"
              >
                <X size={16} />
              </button>

              <div className="text-center space-y-4">
                <div className="inline-flex p-3 rounded-full bg-amber-500/10 text-amber-500">
                  <Star size={32} fill="currentColor" className="animate-bounce" />
                </div>

                <div>
                  <h3 className="text-lg font-bold font-display">{t.rateTitle}</h3>
                  <p className="text-xs text-slate-500 mt-1">{t.rateSub}</p>
                </div>

                {ratingSubmitted ? (
                  <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="py-6 flex flex-col items-center space-y-2 text-emerald-500"
                  >
                    <CheckCircle size={44} />
                    <span className="text-sm font-bold">Rating Saved!</span>
                    <span className="text-xs text-slate-500 font-medium">Syncing profile states...</span>
                  </motion.div>
                ) : (
                  <form onSubmit={handleSubmitRating} className="space-y-4 pt-2">
                    {/* Interactive Star Row */}
                    <div className="flex justify-center items-center gap-1.5 py-1">
                      {[1, 2, 3, 4, 5].map((star) => (
                        <button
                          key={star}
                          type="button"
                          onMouseEnter={() => setHoverRating(star)}
                          onMouseLeave={() => setHoverRating(0)}
                          onClick={() => {
                            setRating(star);
                            if (vibration && navigator.vibrate) navigator.vibrate(10);
                          }}
                          className="p-1.5 cursor-pointer text-amber-400 hover:scale-110 transition-transform bg-transparent border-0"
                        >
                          <Star
                            size={28}
                            fill={(hoverRating || rating) >= star ? 'currentColor' : 'none'}
                          />
                        </button>
                      ))}
                    </div>

                    {/* Feedback message box */}
                    <div>
                      <textarea
                        value={feedback}
                        onChange={(e) => setFeedback(e.target.value)}
                        placeholder={language === 'hi' ? "कृपया बताएं कि आपको CalcNova में क्या पसंद आया या हम इसे कैसे बेहतर बना सकते हैं..." : "Tell us what you love or how we can improve CalcNova..."}
                        maxLength={200}
                        rows={3}
                        className={`w-full p-3 rounded-xl text-xs border focus:outline-hidden focus:ring-1 focus:ring-blue-500 ${
                          isDarkMode ? 'bg-slate-800 text-white border-slate-700' : 'bg-slate-50 text-slate-900 border-slate-200'
                        }`}
                      />
                      <span className="text-[9px] text-slate-500 text-right block mt-1 font-mono">
                        {feedback.length}/200 characters
                      </span>
                    </div>

                    {/* Submit Button */}
                    <button
                      type="submit"
                      className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-full text-xs font-bold flex items-center justify-center gap-1.5 cursor-pointer transition-colors"
                    >
                      <Send size={12} />
                      <span>Submit Feedback</span>
                    </button>
                  </form>
                )}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ========================================================
          PRIVACY POLICY MODAL
          ======================================================== */}
      <AnimatePresence>
        {showPrivacyModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowPrivacyModal(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-xs"
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className={`relative w-full max-w-md rounded-3xl p-6 shadow-2xl z-10 overflow-hidden flex flex-col max-h-[85vh] ${
                isDarkMode ? 'bg-slate-900 text-white border border-slate-800' : 'bg-white text-slate-900 border border-slate-100'
              }`}
            >
              {/* Top Close */}
              <button
                onClick={() => setShowPrivacyModal(false)}
                className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-slate-500/10 cursor-pointer transition-colors bg-transparent border-0"
              >
                <X size={16} />
              </button>

              <div className="flex items-center gap-2 mb-4">
                <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-500">
                  <ShieldCheck size={20} />
                </div>
                <h3 className="text-lg font-bold font-display">{t.privacyTitle}</h3>
              </div>

              {/* Scrollable Privacy Content */}
              <div className="flex-1 overflow-y-auto pr-1 no-scrollbar text-xs space-y-4 text-slate-500 dark:text-slate-400 font-medium pb-2 leading-relaxed">
                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">
                    {language === 'hi' ? "1. शून्य व्यक्तिगत डेटा संग्रह" : "1. Zero Personal Data Collection"}
                  </h4>
                  <p>
                    {language === 'hi' 
                      ? "CalcNova आपकी शैक्षणिक और वित्तीय गोपनीयता का सर्वोपरि सम्मान करता है। सभी कैलकुलेटर (EMI, SIP, GPA, BMI, आदि) आपके ब्राउज़र के भीतर पूरी तरह से क्लाइंट-साइड गणना करते हैं। कोई भी दर्ज किया गया डेटा कभी भी हमारे सर्वर पर प्रेषित या सहेजा नहीं जाता है।"
                      : "CalcNova values your academic and financial privacy above all. Every single calculator (EMI, SIP, GPA, BMI, Unit Converter, Attendance, etc.) computes metrics entirely client-side inside your browser. No data entered, compiled, or resulting is ever sent to or stored on our servers."}
                  </p>
                </div>

                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">
                    {language === 'hi' ? "2. लोकल स्टोरेज सैंडबॉक्स" : "2. Local Storage Sandbox"}
                  </h4>
                  <p>
                    {language === 'hi'
                      ? "आपकी पसंद जैसे कि थीम (लाइट/डार्क/सिस्टम थीम), हैप्टिक फीडबैक, कस्टम फीडबैक और पसंदीदा सूची आपके डिवाइस के सुरक्षित स्थानीय सैंडबॉक्स (localStorage) में संग्रहीत की जाती हैं। यह डेटा आपके डिवाइस से बाहर नहीं जाता है।"
                      : "Preferences like your active UI theme (Light/Dark/System Theme), vibration feedback toggles, custom app ratings, and your pinned Favorites list are securely saved using your browser's local sandbox storage (localStorage). This data never leaves your device."}
                  </p>
                </div>

                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">
                    {language === 'hi' ? "3. कुकीज़ या ट्रैकर का न होना" : "3. No Cookies or Trackers"}
                  </h4>
                  <p>
                    {language === 'hi'
                      ? "CalcNova में कोई विज्ञापन कुकीज़ या विज्ञापन टेलीमेट्री SDK मौजूद नहीं है। आपकी गणना और इतिहास पूरी तरह से सुरक्षित और निजी रहता है।"
                      : "CalcNova does not host tracking cookies, advertising telemetry SDKs, or profile beacons. Your calculation history remains completely private, secure, and fully owned by you."}
                  </p>
                </div>

                <div className="pt-2 border-t dark:border-slate-850 flex items-center justify-between text-[10px]">
                  <span>{language === 'hi' ? "अंतिम संशोधन: जुलाई 2026" : "Last Checked: July 2026"}</span>
                  <span className="text-emerald-500 font-bold flex items-center gap-1">
                    <CheckCircle size={10} /> Certified Secure
                  </span>
                </div>
              </div>

              {/* Close Action */}
              <button
                onClick={() => setShowPrivacyModal(false)}
                className="mt-4 w-full py-2.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-750 text-slate-700 dark:text-slate-200 rounded-full text-xs font-bold transition-colors cursor-pointer"
              >
                {language === 'hi' ? "समझ गया और बंद करें" : "Understood & Close"}
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ========================================================
          TERMS & CONDITIONS MODAL
          ======================================================== */}
      <AnimatePresence>
        {showTermsModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowTermsModal(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-xs"
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className={`relative w-full max-w-md rounded-3xl p-6 shadow-2xl z-10 overflow-hidden flex flex-col max-h-[85vh] ${
                isDarkMode ? 'bg-slate-900 text-white border border-slate-800' : 'bg-white text-slate-900 border border-slate-100'
              }`}
            >
              {/* Top Close */}
              <button
                onClick={() => setShowTermsModal(false)}
                className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-slate-500/10 cursor-pointer transition-colors bg-transparent border-0"
              >
                <X size={16} />
              </button>

              <div className="flex items-center gap-2 mb-4">
                <div className="p-2 rounded-xl bg-orange-500/10 text-orange-500">
                  <FileText size={20} />
                </div>
                <h3 className="text-lg font-bold font-display">{t.termsModalTitle}</h3>
              </div>

              {/* Scrollable Terms Content */}
              <div className="flex-1 overflow-y-auto pr-1 no-scrollbar text-xs space-y-4 text-slate-500 dark:text-slate-400 font-medium pb-2 leading-relaxed">
                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">{t.termsContent1}</h4>
                  <p>{t.termsContent1Text}</p>
                </div>

                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">{t.termsContent2}</h4>
                  <p>{t.termsContent2Text}</p>
                </div>

                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">{t.termsContent3}</h4>
                  <p>{t.termsContent3Text}</p>
                </div>

                <div>
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 mb-1">{t.termsContent4}</h4>
                  <p>{t.termsContent4Text}</p>
                </div>

                <div className="pt-2 border-t dark:border-slate-850 flex items-center justify-between text-[10px]">
                  <span>{language === 'hi' ? "जुलाई २०२६ से लागू" : "Effective: July 2026"}</span>
                  <span className="text-orange-500 font-bold flex items-center gap-1">
                    <CheckCircle size={10} /> Active Terms
                  </span>
                </div>
              </div>

              {/* Close Action */}
              <button
                onClick={() => setShowTermsModal(false)}
                className="mt-4 w-full py-2.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-750 text-slate-700 dark:text-slate-200 rounded-full text-xs font-bold transition-colors cursor-pointer"
              >
                {language === 'hi' ? "स्वीकार करें और बंद करें" : "Accept & Close"}
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ========================================================
          CONTACT US MODAL
          ======================================================== */}
      <AnimatePresence>
        {showContactModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowContactModal(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-xs"
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className={`relative w-full max-w-sm rounded-3xl p-6 shadow-2xl z-10 overflow-hidden ${
                isDarkMode ? 'bg-slate-900 text-white border border-slate-800' : 'bg-white text-slate-900 border border-slate-100'
              }`}
            >
              {/* Top Close Button */}
              <button
                onClick={() => setShowContactModal(false)}
                className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-slate-500/10 cursor-pointer transition-colors bg-transparent border-0"
              >
                <X size={16} />
              </button>

              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-cyan-500/10 text-cyan-500">
                    <PhoneCall size={20} />
                  </div>
                  <div>
                    <h3 className="text-base font-bold font-display">{t.contactModalTitle}</h3>
                    <p className="text-[10px] text-slate-500">{t.contactModalDesc}</p>
                  </div>
                </div>

                {contactSuccessMsg ? (
                  <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="py-8 flex flex-col items-center space-y-2 text-cyan-500 text-center"
                  >
                    <CheckCircle size={44} />
                    <span className="text-sm font-bold">{language === 'hi' ? "संदेश प्रेषित!" : "Message Submitted!"}</span>
                    <span className="text-xs text-slate-500 font-medium">{language === 'hi' ? "हमारी सहायता टीम जल्द ही संपर्क करेगी..." : "Our support desk will handle it shortly..."}</span>
                  </motion.div>
                ) : (
                  <form onSubmit={handleContactSubmit} className="space-y-3.5 pt-1">
                    {contactErr && (
                      <div className="p-2 text-center rounded-xl text-[10px] font-bold bg-red-500/15 text-red-500 leading-snug">
                        ⚠️ {contactErr}
                      </div>
                    )}

                    {/* Name */}
                    <div className="space-y-1">
                      <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider pl-1">{t.contactFormName}</label>
                      <input
                        type="text"
                        value={contactName}
                        onChange={(e) => setContactName(e.target.value)}
                        placeholder="John Doe"
                        className={`w-full p-2.5 rounded-xl text-xs border focus:outline-hidden focus:ring-1 focus:ring-cyan-500 ${
                          isDarkMode ? 'bg-slate-800 text-white border-slate-700' : 'bg-slate-50 text-slate-900 border-slate-200'
                        }`}
                      />
                    </div>

                    {/* Email */}
                    <div className="space-y-1">
                      <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider pl-1">{t.contactFormEmail}</label>
                      <input
                        type="email"
                        value={contactEmail}
                        onChange={(e) => setContactEmail(e.target.value)}
                        placeholder="john@example.com"
                        className={`w-full p-2.5 rounded-xl text-xs border focus:outline-hidden focus:ring-1 focus:ring-cyan-500 ${
                          isDarkMode ? 'bg-slate-800 text-white border-slate-700' : 'bg-slate-50 text-slate-900 border-slate-200'
                        }`}
                      />
                    </div>

                    {/* Category Selector */}
                    <div className="space-y-1">
                      <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider pl-1">{t.contactFormCategory}</label>
                      <select
                        value={contactCategory}
                        onChange={(e) => setContactCategory(e.target.value)}
                        className={`w-full p-2.5 rounded-xl text-xs border focus:outline-hidden focus:ring-1 focus:ring-cyan-500 ${
                          isDarkMode ? 'bg-slate-800 text-white border-slate-700' : 'bg-slate-50 text-slate-900 border-slate-200'
                        }`}
                      >
                        <option value="bug">{t.contactFormCategoryBug}</option>
                        <option value="feature">{t.contactFormCategoryFeature}</option>
                        <option value="support">{t.contactFormCategorySupport}</option>
                      </select>
                    </div>

                    {/* Message */}
                    <div className="space-y-1">
                      <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider pl-1">{language === 'hi' ? 'संदेश' : 'Message'}</label>
                      <textarea
                        value={contactMessage}
                        onChange={(e) => setContactMessage(e.target.value)}
                        placeholder={t.contactFormMessage}
                        rows={3}
                        className={`w-full p-2.5 rounded-xl text-xs border focus:outline-hidden focus:ring-1 focus:ring-cyan-500 ${
                          isDarkMode ? 'bg-slate-800 text-white border-slate-700' : 'bg-slate-50 text-slate-900 border-slate-200'
                        }`}
                      />
                    </div>

                    <button
                      type="submit"
                      className="w-full py-2.5 bg-cyan-600 hover:bg-cyan-700 text-white rounded-full text-xs font-bold flex items-center justify-center gap-1.5 cursor-pointer transition-colors"
                    >
                      <Send size={12} />
                      <span>{t.contactSubmitBtn}</span>
                    </button>
                  </form>
                )}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* ========================================================
          ABOUT APP MODAL
          ======================================================== */}
      <AnimatePresence>
        {showAboutModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowAboutModal(false)}
              className="absolute inset-0 bg-black/60 backdrop-blur-xs"
            />

            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className={`relative w-full max-w-md rounded-3xl p-6 shadow-2xl z-10 overflow-hidden flex flex-col max-h-[85vh] ${
                isDarkMode ? 'bg-slate-900 text-white border border-slate-800' : 'bg-white text-slate-900 border border-slate-100'
              }`}
            >
              {/* Top Close */}
              <button
                onClick={() => setShowAboutModal(false)}
                className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-slate-500/10 cursor-pointer transition-colors bg-transparent border-0"
              >
                <X size={16} />
              </button>

              <div className="flex items-center gap-2 mb-4">
                <div className="p-2 rounded-xl bg-purple-500/10 text-purple-400">
                  <Info size={20} />
                </div>
                <h3 className="text-lg font-bold font-display">{t.aboutTitle}</h3>
              </div>

              {/* Scrollable About Content */}
              <div className="flex-1 overflow-y-auto pr-1 no-scrollbar text-xs space-y-4 pb-2 text-slate-500 dark:text-slate-400 font-medium">
                <div className="text-center py-4 space-y-1.5 bg-blue-500/5 dark:bg-blue-500/10 rounded-2xl border border-blue-500/10">
                  <span className="text-2xl font-extrabold font-display tracking-tight text-blue-600 dark:text-blue-400 block">
                    {t.aboutHeader}
                  </span>
                  <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider block">
                    {t.aboutSubHeader}
                  </span>
                  <span className="px-2.5 py-0.5 rounded-full text-[10px] bg-blue-500 text-white font-mono font-semibold inline-block">
                    v2.1.0 (Stable)
                  </span>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider text-[10px]">{t.aboutDescTitle}</h4>
                  <p className="leading-relaxed">
                    {t.aboutDescText}
                  </p>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider text-[10px]">{t.aboutModulesTitle}</h4>
                  <ul className="grid grid-cols-2 gap-2 text-[11px] font-semibold">
                    <li className="flex items-center gap-1 bg-slate-50 dark:bg-slate-850 p-2 rounded-lg text-slate-700 dark:text-slate-300">
                      🟢 {language === 'hi' ? 'वित्तीय कैलकुलेटर' : 'Finance Suite'}
                    </li>
                    <li className="flex items-center gap-1 bg-slate-50 dark:bg-slate-850 p-2 rounded-lg text-slate-700 dark:text-slate-300">
                      🟢 {language === 'hi' ? 'शैक्षणिक विश्लेषक' : 'Education Suite'}
                    </li>
                    <li className="flex items-center gap-1 bg-slate-50 dark:bg-slate-850 p-2 rounded-lg text-slate-700 dark:text-slate-300">
                      🟢 {language === 'hi' ? 'स्वास्थ्य ट्रैकर' : 'Health Tracker'}
                    </li>
                    <li className="flex items-center gap-1 bg-slate-50 dark:bg-slate-850 p-2 rounded-lg text-slate-700 dark:text-slate-300">
                      🟢 {language === 'hi' ? 'दैनिक उपयोगिताएँ' : 'Daily Utilities'}
                    </li>
                    <li className="flex items-center gap-1 bg-slate-50 dark:bg-slate-850 p-2 rounded-lg text-slate-700 dark:text-slate-300">
                      🟢 {language === 'hi' ? 'इकाई कनवर्टर' : 'Unit Converter'}
                    </li>
                    <li className="flex items-center gap-1 bg-slate-50 dark:bg-slate-850 p-2 rounded-lg text-slate-700 dark:text-slate-300">
                      🟢 {language === 'hi' ? 'समय एवं दिनांक' : 'Time & Date'}
                    </li>
                  </ul>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider text-[10px]">{t.aboutChangelogTitle}</h4>
                  <div className="space-y-1.5 font-mono text-[10px] text-slate-500">
                    <p className="flex justify-between border-b dark:border-slate-800 pb-1">
                      <span>• English & Hindi translation logs</span>
                      <span className="text-emerald-500 font-bold">Done</span>
                    </p>
                    <p className="flex justify-between border-b dark:border-slate-800 pb-1">
                      <span>• Explicit System Theme detection</span>
                      <span className="text-emerald-500 font-bold">Done</span>
                    </p>
                    <p className="flex justify-between border-b dark:border-slate-800 pb-1">
                      <span>• Contact Us validator and terms sheet</span>
                      <span className="text-emerald-500 font-bold">Done</span>
                    </p>
                    <p className="flex justify-between pb-1">
                      <span>• Factory Reset state restoration</span>
                      <span className="text-emerald-500 font-bold">Done</span>
                    </p>
                  </div>
                </div>

                <div className="pt-2 border-t dark:border-slate-850 flex items-center justify-between text-[10px]">
                  <span>Engine: Vite + React 18 + TS</span>
                  <span className="text-blue-500 font-bold flex items-center gap-0.5">
                    <Heart size={10} fill="currentColor" /> Powered by Antigravity
                  </span>
                </div>
              </div>

              {/* Close Action */}
              <button
                onClick={() => setShowAboutModal(false)}
                className="mt-4 w-full py-2.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-750 text-slate-700 dark:text-slate-200 rounded-full text-xs font-bold transition-colors cursor-pointer"
              >
                Close About
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
